// Question
export const GET_QUESTIONS_REQUEST = "question/GET_QUESTIONS_REQUEST";
export const GET_QUESTIONS_SUCCESS = "question/GET_QUESTIONS_SUCCESS";
export const GET_QUESTIONS_FAILURE = "question/GET_QUESTIONS_FAILURE";
export const POST_ANSWER_REQUEST = "question/POST_ANSWER_REQUEST";
export const CLEAR_DATA_REQUEST = "question/CLEAR_DATA_REQUEST";
